### PR TITLE
Update gradle and java versions to meet with latests IDE requrements

### PR DESCRIPTION
**Pull request by Gelassen**
I updated gradle version to 8.0 and java version to meet with latest Android Studio requirements.

### CODE REVIEW

**Comment by mhsmith** [comment]
It looks like you forgot to include most of the files.

**Comment by Gelassen** [comment]
> It looks like you forgot to include most of the files.

Yes, you are right. Please check pushed files. 

Also please note I have updated target sdk to the 33. Now it is mandatory requirement for app to be published over Google Play. I know you not going to publish this sample app, but it is good to confirm chaquopy meets with this version as well.

**Comment by Gelassen** [comment]
It has the same issues like https://github.com/chaquo/chaquopy-console/pull/9 PR, but I believe as soon as it passes test coverage it is fine to merge. In case of this app launch over emulator should be fine. (passed API 28 and API 33)

**Comment by mhsmith** [comment]
See https://github.com/chaquo/chaquopy-console/pull/9 for why I reverted some files.

Thanks for the contribution!

**Pull request merged**
